version: 2.1
orbs:
  node: circleci/node@4
  codecov: codecov/codecov@1
jobs:
  test:
    executor:
      name: node/default
      tag: 'current'
    steps:
      - checkout
      - node/install-packages
      - run:
          name: lint
          command: npm run lint
      - run:
          name: build
          command: npm run build
      - codecov/upload
  release:
    executor:
      name: node/default
      tag: 'current'
    steps:
      - checkout
      - node/install-packages
      - run: npm run build
      - run: cd dist && npx semantic-release

workflows:
  version: 2
  test_and_release:
    jobs:
      - test
      - release:
          filters:
            branches:
              only:
                - master
          context:
            - npm
          requires:
            - test
